//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM-Beziehungsmetadaten

[assembly: EdmRelationshipAttribute("Zepheus.Database", "FK_Equip_Character", "Character", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(Zepheus.Database.Character), "Equip", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Zepheus.Database.DatabaseEquip), true)]
[assembly: EdmRelationshipAttribute("Zepheus.Database", "FK_Item_Character1", "Character", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(Zepheus.Database.Character), "Item", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Zepheus.Database.DatabaseItem), true)]
[assembly: EdmRelationshipAttribute("Zepheus.Database", "FK_Skills_Character", "Character", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(Zepheus.Database.Character), "Skill", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Zepheus.Database.DatabaseSkill), true)]
[assembly: EdmRelationshipAttribute("Zepheus.Database", "FK_Character_Guild", "Guild", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Zepheus.Database.Guild), "Character", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Zepheus.Database.Character), true)]
[assembly: EdmRelationshipAttribute("Zepheus.Database", "FK_PartyMatchingSystem_Character", "Character", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(Zepheus.Database.Character), "PartyMatchingSystem", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Zepheus.Database.PartyMatchingSystem), true)]
[assembly: EdmRelationshipAttribute("Zepheus.Database", "FK_Party_Character", "Character", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(Zepheus.Database.Character), "Party", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Zepheus.Database.Party), true)]

#endregion

namespace Zepheus.Database
{
    #region Kontexte
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    public partial class WorldEntity : ObjectContext
    {
        #region Konstruktoren
    
        /// <summary>
        /// Initialisiert ein neues WorldEntity-Objekt mithilfe der in Abschnitt 'WorldEntity' der Anwendungskonfigurationsdatei gefundenen Verbindungszeichenfolge.
        /// </summary>
        public WorldEntity() : base("name=WorldEntity", "WorldEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues WorldEntity-Objekt.
        /// </summary>
        public WorldEntity(string connectionString) : base(connectionString, "WorldEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisiert ein neues WorldEntity-Objekt.
        /// </summary>
        public WorldEntity(EntityConnection connection) : base(connection, "WorldEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partielle Methoden
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet-Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Character> Characters
        {
            get
            {
                if ((_Characters == null))
                {
                    _Characters = base.CreateObjectSet<Character>("Characters");
                }
                return _Characters;
            }
        }
        private ObjectSet<Character> _Characters;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<DatabaseEquip> DatabaseEquips
        {
            get
            {
                if ((_DatabaseEquips == null))
                {
                    _DatabaseEquips = base.CreateObjectSet<DatabaseEquip>("DatabaseEquips");
                }
                return _DatabaseEquips;
            }
        }
        private ObjectSet<DatabaseEquip> _DatabaseEquips;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<DatabaseItem> DatabaseItems
        {
            get
            {
                if ((_DatabaseItems == null))
                {
                    _DatabaseItems = base.CreateObjectSet<DatabaseItem>("DatabaseItems");
                }
                return _DatabaseItems;
            }
        }
        private ObjectSet<DatabaseItem> _DatabaseItems;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<DatabaseSkill> DatabaseSkills
        {
            get
            {
                if ((_DatabaseSkills == null))
                {
                    _DatabaseSkills = base.CreateObjectSet<DatabaseSkill>("DatabaseSkills");
                }
                return _DatabaseSkills;
            }
        }
        private ObjectSet<DatabaseSkill> _DatabaseSkills;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Guild> Guilds
        {
            get
            {
                if ((_Guilds == null))
                {
                    _Guilds = base.CreateObjectSet<Guild>("Guilds");
                }
                return _Guilds;
            }
        }
        private ObjectSet<Guild> _Guilds;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<PartyMatchingSystem> PartyMatchingSystems
        {
            get
            {
                if ((_PartyMatchingSystems == null))
                {
                    _PartyMatchingSystems = base.CreateObjectSet<PartyMatchingSystem>("PartyMatchingSystems");
                }
                return _PartyMatchingSystems;
            }
        }
        private ObjectSet<PartyMatchingSystem> _PartyMatchingSystems;
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        public ObjectSet<Party> Parties
        {
            get
            {
                if ((_Parties == null))
                {
                    _Parties = base.CreateObjectSet<Party>("Parties");
                }
                return _Parties;
            }
        }
        private ObjectSet<Party> _Parties;

        #endregion

        #region AddTo-Methoden
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Characters'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToCharacters(Character character)
        {
            base.AddObject("Characters", character);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'DatabaseEquips'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToDatabaseEquips(DatabaseEquip databaseEquip)
        {
            base.AddObject("DatabaseEquips", databaseEquip);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'DatabaseItems'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToDatabaseItems(DatabaseItem databaseItem)
        {
            base.AddObject("DatabaseItems", databaseItem);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'DatabaseSkills'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToDatabaseSkills(DatabaseSkill databaseSkill)
        {
            base.AddObject("DatabaseSkills", databaseSkill);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Guilds'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToGuilds(Guild guild)
        {
            base.AddObject("Guilds", guild);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'PartyMatchingSystems'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToPartyMatchingSystems(PartyMatchingSystem partyMatchingSystem)
        {
            base.AddObject("PartyMatchingSystems", partyMatchingSystem);
        }
    
        /// <summary>
        /// Veraltete Methode zum Hinzufügen eines neuen Objekts zum EntitySet 'Parties'. Verwenden Sie stattdessen die Methode '.Add' der zugeordneten Eigenschaft 'ObjectSet&lt;T&gt;'.
        /// </summary>
        public void AddToParties(Party party)
        {
            base.AddObject("Parties", party);
        }

        #endregion

    }

    #endregion

    #region Entitäten
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Zepheus.Database", Name="Character")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Character : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Character-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft ID.</param>
        /// <param name="accountID">Anfangswert der Eigenschaft AccountID.</param>
        /// <param name="name">Anfangswert der Eigenschaft Name.</param>
        /// <param name="slot">Anfangswert der Eigenschaft Slot.</param>
        /// <param name="map">Anfangswert der Eigenschaft Map.</param>
        /// <param name="charLevel">Anfangswert der Eigenschaft CharLevel.</param>
        /// <param name="job">Anfangswert der Eigenschaft Job.</param>
        /// <param name="male">Anfangswert der Eigenschaft Male.</param>
        /// <param name="hP">Anfangswert der Eigenschaft HP.</param>
        /// <param name="sP">Anfangswert der Eigenschaft SP.</param>
        /// <param name="hPStones">Anfangswert der Eigenschaft HPStones.</param>
        /// <param name="sPStones">Anfangswert der Eigenschaft SPStones.</param>
        /// <param name="exp">Anfangswert der Eigenschaft Exp.</param>
        /// <param name="fame">Anfangswert der Eigenschaft Fame.</param>
        /// <param name="money">Anfangswert der Eigenschaft Money.</param>
        /// <param name="hair">Anfangswert der Eigenschaft Hair.</param>
        /// <param name="hairColor">Anfangswert der Eigenschaft HairColor.</param>
        /// <param name="face">Anfangswert der Eigenschaft Face.</param>
        /// <param name="xPos">Anfangswert der Eigenschaft XPos.</param>
        /// <param name="yPos">Anfangswert der Eigenschaft YPos.</param>
        /// <param name="statPoints">Anfangswert der Eigenschaft StatPoints.</param>
        /// <param name="strStats">Anfangswert der Eigenschaft StrStats.</param>
        /// <param name="endStats">Anfangswert der Eigenschaft EndStats.</param>
        /// <param name="dexStats">Anfangswert der Eigenschaft DexStats.</param>
        /// <param name="intStats">Anfangswert der Eigenschaft IntStats.</param>
        /// <param name="sprStats">Anfangswert der Eigenschaft SprStats.</param>
        /// <param name="usablePoints">Anfangswert der Eigenschaft UsablePoints.</param>
        public static Character CreateCharacter(global::System.Int32 id, global::System.Int32 accountID, global::System.String name, global::System.Byte slot, global::System.Byte map, global::System.Byte charLevel, global::System.Byte job, global::System.Boolean male, global::System.Int32 hP, global::System.Int32 sP, global::System.Int16 hPStones, global::System.Int16 sPStones, global::System.Int64 exp, global::System.Int32 fame, global::System.Int64 money, global::System.Byte hair, global::System.Byte hairColor, global::System.Byte face, global::System.Int32 xPos, global::System.Int32 yPos, global::System.Byte statPoints, global::System.Byte strStats, global::System.Byte endStats, global::System.Byte dexStats, global::System.Byte intStats, global::System.Byte sprStats, global::System.Byte usablePoints)
        {
            Character character = new Character();
            character.ID = id;
            character.AccountID = accountID;
            character.Name = name;
            character.Slot = slot;
            character.Map = map;
            character.CharLevel = charLevel;
            character.Job = job;
            character.Male = male;
            character.HP = hP;
            character.SP = sP;
            character.HPStones = hPStones;
            character.SPStones = sPStones;
            character.Exp = exp;
            character.Fame = fame;
            character.Money = money;
            character.Hair = hair;
            character.HairColor = hairColor;
            character.Face = face;
            character.XPos = xPos;
            character.YPos = yPos;
            character.StatPoints = statPoints;
            character.StrStats = strStats;
            character.EndStats = endStats;
            character.DexStats = dexStats;
            character.IntStats = intStats;
            character.SprStats = sprStats;
            character.UsablePoints = usablePoints;
            return character;
        }

        #endregion

        #region Einfache Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccountID
        {
            get
            {
                return _AccountID;
            }
            set
            {
                OnAccountIDChanging(value);
                ReportPropertyChanging("AccountID");
                _AccountID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccountID");
                OnAccountIDChanged();
            }
        }
        private global::System.Int32 _AccountID;
        partial void OnAccountIDChanging(global::System.Int32 value);
        partial void OnAccountIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Slot
        {
            get
            {
                return _Slot;
            }
            set
            {
                OnSlotChanging(value);
                ReportPropertyChanging("Slot");
                _Slot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Slot");
                OnSlotChanged();
            }
        }
        private global::System.Byte _Slot;
        partial void OnSlotChanging(global::System.Byte value);
        partial void OnSlotChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Map
        {
            get
            {
                return _Map;
            }
            set
            {
                OnMapChanging(value);
                ReportPropertyChanging("Map");
                _Map = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Map");
                OnMapChanged();
            }
        }
        private global::System.Byte _Map;
        partial void OnMapChanging(global::System.Byte value);
        partial void OnMapChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CharLevel
        {
            get
            {
                return _CharLevel;
            }
            set
            {
                OnCharLevelChanging(value);
                ReportPropertyChanging("CharLevel");
                _CharLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CharLevel");
                OnCharLevelChanged();
            }
        }
        private global::System.Byte _CharLevel;
        partial void OnCharLevelChanging(global::System.Byte value);
        partial void OnCharLevelChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Job
        {
            get
            {
                return _Job;
            }
            set
            {
                OnJobChanging(value);
                ReportPropertyChanging("Job");
                _Job = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Job");
                OnJobChanged();
            }
        }
        private global::System.Byte _Job;
        partial void OnJobChanging(global::System.Byte value);
        partial void OnJobChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Male
        {
            get
            {
                return _Male;
            }
            set
            {
                OnMaleChanging(value);
                ReportPropertyChanging("Male");
                _Male = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Male");
                OnMaleChanged();
            }
        }
        private global::System.Boolean _Male;
        partial void OnMaleChanging(global::System.Boolean value);
        partial void OnMaleChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HP
        {
            get
            {
                return _HP;
            }
            set
            {
                OnHPChanging(value);
                ReportPropertyChanging("HP");
                _HP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HP");
                OnHPChanged();
            }
        }
        private global::System.Int32 _HP;
        partial void OnHPChanging(global::System.Int32 value);
        partial void OnHPChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SP
        {
            get
            {
                return _SP;
            }
            set
            {
                OnSPChanging(value);
                ReportPropertyChanging("SP");
                _SP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SP");
                OnSPChanged();
            }
        }
        private global::System.Int32 _SP;
        partial void OnSPChanging(global::System.Int32 value);
        partial void OnSPChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 HPStones
        {
            get
            {
                return _HPStones;
            }
            set
            {
                OnHPStonesChanging(value);
                ReportPropertyChanging("HPStones");
                _HPStones = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HPStones");
                OnHPStonesChanged();
            }
        }
        private global::System.Int16 _HPStones;
        partial void OnHPStonesChanging(global::System.Int16 value);
        partial void OnHPStonesChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 SPStones
        {
            get
            {
                return _SPStones;
            }
            set
            {
                OnSPStonesChanging(value);
                ReportPropertyChanging("SPStones");
                _SPStones = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SPStones");
                OnSPStonesChanged();
            }
        }
        private global::System.Int16 _SPStones;
        partial void OnSPStonesChanging(global::System.Int16 value);
        partial void OnSPStonesChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Exp
        {
            get
            {
                return _Exp;
            }
            set
            {
                OnExpChanging(value);
                ReportPropertyChanging("Exp");
                _Exp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Exp");
                OnExpChanged();
            }
        }
        private global::System.Int64 _Exp;
        partial void OnExpChanging(global::System.Int64 value);
        partial void OnExpChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Fame
        {
            get
            {
                return _Fame;
            }
            set
            {
                OnFameChanging(value);
                ReportPropertyChanging("Fame");
                _Fame = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fame");
                OnFameChanged();
            }
        }
        private global::System.Int32 _Fame;
        partial void OnFameChanging(global::System.Int32 value);
        partial void OnFameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Money
        {
            get
            {
                return _Money;
            }
            set
            {
                OnMoneyChanging(value);
                ReportPropertyChanging("Money");
                _Money = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Money");
                OnMoneyChanged();
            }
        }
        private global::System.Int64 _Money;
        partial void OnMoneyChanging(global::System.Int64 value);
        partial void OnMoneyChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Hair
        {
            get
            {
                return _Hair;
            }
            set
            {
                OnHairChanging(value);
                ReportPropertyChanging("Hair");
                _Hair = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hair");
                OnHairChanged();
            }
        }
        private global::System.Byte _Hair;
        partial void OnHairChanging(global::System.Byte value);
        partial void OnHairChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte HairColor
        {
            get
            {
                return _HairColor;
            }
            set
            {
                OnHairColorChanging(value);
                ReportPropertyChanging("HairColor");
                _HairColor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HairColor");
                OnHairColorChanged();
            }
        }
        private global::System.Byte _HairColor;
        partial void OnHairColorChanging(global::System.Byte value);
        partial void OnHairColorChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Face
        {
            get
            {
                return _Face;
            }
            set
            {
                OnFaceChanging(value);
                ReportPropertyChanging("Face");
                _Face = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Face");
                OnFaceChanged();
            }
        }
        private global::System.Byte _Face;
        partial void OnFaceChanging(global::System.Byte value);
        partial void OnFaceChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 XPos
        {
            get
            {
                return _XPos;
            }
            set
            {
                OnXPosChanging(value);
                ReportPropertyChanging("XPos");
                _XPos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("XPos");
                OnXPosChanged();
            }
        }
        private global::System.Int32 _XPos;
        partial void OnXPosChanging(global::System.Int32 value);
        partial void OnXPosChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 YPos
        {
            get
            {
                return _YPos;
            }
            set
            {
                OnYPosChanging(value);
                ReportPropertyChanging("YPos");
                _YPos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YPos");
                OnYPosChanged();
            }
        }
        private global::System.Int32 _YPos;
        partial void OnYPosChanging(global::System.Int32 value);
        partial void OnYPosChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte StatPoints
        {
            get
            {
                return _StatPoints;
            }
            set
            {
                OnStatPointsChanging(value);
                ReportPropertyChanging("StatPoints");
                _StatPoints = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatPoints");
                OnStatPointsChanged();
            }
        }
        private global::System.Byte _StatPoints;
        partial void OnStatPointsChanging(global::System.Byte value);
        partial void OnStatPointsChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte StrStats
        {
            get
            {
                return _StrStats;
            }
            set
            {
                OnStrStatsChanging(value);
                ReportPropertyChanging("StrStats");
                _StrStats = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StrStats");
                OnStrStatsChanged();
            }
        }
        private global::System.Byte _StrStats;
        partial void OnStrStatsChanging(global::System.Byte value);
        partial void OnStrStatsChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte EndStats
        {
            get
            {
                return _EndStats;
            }
            set
            {
                OnEndStatsChanging(value);
                ReportPropertyChanging("EndStats");
                _EndStats = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndStats");
                OnEndStatsChanged();
            }
        }
        private global::System.Byte _EndStats;
        partial void OnEndStatsChanging(global::System.Byte value);
        partial void OnEndStatsChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte DexStats
        {
            get
            {
                return _DexStats;
            }
            set
            {
                OnDexStatsChanging(value);
                ReportPropertyChanging("DexStats");
                _DexStats = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DexStats");
                OnDexStatsChanged();
            }
        }
        private global::System.Byte _DexStats;
        partial void OnDexStatsChanging(global::System.Byte value);
        partial void OnDexStatsChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte IntStats
        {
            get
            {
                return _IntStats;
            }
            set
            {
                OnIntStatsChanging(value);
                ReportPropertyChanging("IntStats");
                _IntStats = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IntStats");
                OnIntStatsChanged();
            }
        }
        private global::System.Byte _IntStats;
        partial void OnIntStatsChanging(global::System.Byte value);
        partial void OnIntStatsChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte SprStats
        {
            get
            {
                return _SprStats;
            }
            set
            {
                OnSprStatsChanging(value);
                ReportPropertyChanging("SprStats");
                _SprStats = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SprStats");
                OnSprStatsChanged();
            }
        }
        private global::System.Byte _SprStats;
        partial void OnSprStatsChanging(global::System.Byte value);
        partial void OnSprStatsChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CurrentTitle
        {
            get
            {
                return _CurrentTitle;
            }
            set
            {
                OnCurrentTitleChanging(value);
                ReportPropertyChanging("CurrentTitle");
                _CurrentTitle = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentTitle");
                OnCurrentTitleChanged();
            }
        }
        private Nullable<global::System.Int32> _CurrentTitle;
        partial void OnCurrentTitleChanging(Nullable<global::System.Int32> value);
        partial void OnCurrentTitleChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] QuickBar
        {
            get
            {
                return StructuralObject.GetValidValue(_QuickBar);
            }
            set
            {
                OnQuickBarChanging(value);
                ReportPropertyChanging("QuickBar");
                _QuickBar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QuickBar");
                OnQuickBarChanged();
            }
        }
        private global::System.Byte[] _QuickBar;
        partial void OnQuickBarChanging(global::System.Byte[] value);
        partial void OnQuickBarChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] QuickBarState
        {
            get
            {
                return StructuralObject.GetValidValue(_QuickBarState);
            }
            set
            {
                OnQuickBarStateChanging(value);
                ReportPropertyChanging("QuickBarState");
                _QuickBarState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("QuickBarState");
                OnQuickBarStateChanged();
            }
        }
        private global::System.Byte[] _QuickBarState;
        partial void OnQuickBarStateChanging(global::System.Byte[] value);
        partial void OnQuickBarStateChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Shortcuts
        {
            get
            {
                return StructuralObject.GetValidValue(_Shortcuts);
            }
            set
            {
                OnShortcutsChanging(value);
                ReportPropertyChanging("Shortcuts");
                _Shortcuts = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Shortcuts");
                OnShortcutsChanged();
            }
        }
        private global::System.Byte[] _Shortcuts;
        partial void OnShortcutsChanging(global::System.Byte[] value);
        partial void OnShortcutsChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] GameSettings
        {
            get
            {
                return StructuralObject.GetValidValue(_GameSettings);
            }
            set
            {
                OnGameSettingsChanging(value);
                ReportPropertyChanging("GameSettings");
                _GameSettings = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GameSettings");
                OnGameSettingsChanged();
            }
        }
        private global::System.Byte[] _GameSettings;
        partial void OnGameSettingsChanging(global::System.Byte[] value);
        partial void OnGameSettingsChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] ClientSettings
        {
            get
            {
                return StructuralObject.GetValidValue(_ClientSettings);
            }
            set
            {
                OnClientSettingsChanging(value);
                ReportPropertyChanging("ClientSettings");
                _ClientSettings = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientSettings");
                OnClientSettingsChanged();
            }
        }
        private global::System.Byte[] _ClientSettings;
        partial void OnClientSettingsChanging(global::System.Byte[] value);
        partial void OnClientSettingsChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte UsablePoints
        {
            get
            {
                return _UsablePoints;
            }
            set
            {
                OnUsablePointsChanging(value);
                ReportPropertyChanging("UsablePoints");
                _UsablePoints = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UsablePoints");
                OnUsablePointsChanged();
            }
        }
        private global::System.Byte _UsablePoints;
        partial void OnUsablePointsChanging(global::System.Byte value);
        partial void OnUsablePointsChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GuildID
        {
            get
            {
                return _GuildID;
            }
            set
            {
                OnGuildIDChanging(value);
                ReportPropertyChanging("GuildID");
                _GuildID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GuildID");
                OnGuildIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GuildID;
        partial void OnGuildIDChanging(Nullable<global::System.Int32> value);
        partial void OnGuildIDChanged();

        #endregion

        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_Equip_Character", "Equip")]
        public EntityCollection<DatabaseEquip> Equips
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DatabaseEquip>("Zepheus.Database.FK_Equip_Character", "Equip");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DatabaseEquip>("Zepheus.Database.FK_Equip_Character", "Equip", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_Item_Character1", "Item")]
        public EntityCollection<DatabaseItem> Items
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DatabaseItem>("Zepheus.Database.FK_Item_Character1", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DatabaseItem>("Zepheus.Database.FK_Item_Character1", "Item", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_Skills_Character", "Skill")]
        public EntityCollection<DatabaseSkill> Skills
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DatabaseSkill>("Zepheus.Database.FK_Skills_Character", "Skill");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DatabaseSkill>("Zepheus.Database.FK_Skills_Character", "Skill", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_Character_Guild", "Guild")]
        public Guild Guild
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Guild>("Zepheus.Database.FK_Character_Guild", "Guild").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Guild>("Zepheus.Database.FK_Character_Guild", "Guild").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Guild> GuildReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Guild>("Zepheus.Database.FK_Character_Guild", "Guild");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Guild>("Zepheus.Database.FK_Character_Guild", "Guild", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_PartyMatchingSystem_Character", "PartyMatchingSystem")]
        public EntityCollection<PartyMatchingSystem> PartyMatchingSystems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PartyMatchingSystem>("Zepheus.Database.FK_PartyMatchingSystem_Character", "PartyMatchingSystem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PartyMatchingSystem>("Zepheus.Database.FK_PartyMatchingSystem_Character", "PartyMatchingSystem", value);
                }
            }
        }
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_Party_Character", "Party")]
        public Party Party
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Party>("Zepheus.Database.FK_Party_Character", "Party").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Party>("Zepheus.Database.FK_Party_Character", "Party").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Party> PartyReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Party>("Zepheus.Database.FK_Party_Character", "Party");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Party>("Zepheus.Database.FK_Party_Character", "Party", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Zepheus.Database", Name="DatabaseEquip")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DatabaseEquip : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues DatabaseEquip-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft ID.</param>
        /// <param name="owner">Anfangswert der Eigenschaft Owner.</param>
        /// <param name="slot">Anfangswert der Eigenschaft Slot.</param>
        /// <param name="equipID">Anfangswert der Eigenschaft EquipID.</param>
        /// <param name="upgrades">Anfangswert der Eigenschaft Upgrades.</param>
        /// <param name="incStr">Anfangswert der Eigenschaft IncStr.</param>
        /// <param name="incEnd">Anfangswert der Eigenschaft IncEnd.</param>
        /// <param name="incDex">Anfangswert der Eigenschaft IncDex.</param>
        /// <param name="incInt">Anfangswert der Eigenschaft IncInt.</param>
        /// <param name="incSpr">Anfangswert der Eigenschaft IncSpr.</param>
        public static DatabaseEquip CreateDatabaseEquip(global::System.Int32 id, global::System.Int32 owner, global::System.Int16 slot, global::System.Int32 equipID, global::System.Byte upgrades, global::System.Byte incStr, global::System.Byte incEnd, global::System.Byte incDex, global::System.Byte incInt, global::System.Byte incSpr)
        {
            DatabaseEquip databaseEquip = new DatabaseEquip();
            databaseEquip.ID = id;
            databaseEquip.Owner = owner;
            databaseEquip.Slot = slot;
            databaseEquip.EquipID = equipID;
            databaseEquip.Upgrades = upgrades;
            databaseEquip.IncStr = incStr;
            databaseEquip.IncEnd = incEnd;
            databaseEquip.IncDex = incDex;
            databaseEquip.IncInt = incInt;
            databaseEquip.IncSpr = incSpr;
            return databaseEquip;
        }

        #endregion

        #region Einfache Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Owner
        {
            get
            {
                return _Owner;
            }
            set
            {
                OnOwnerChanging(value);
                ReportPropertyChanging("Owner");
                _Owner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Owner");
                OnOwnerChanged();
            }
        }
        private global::System.Int32 _Owner;
        partial void OnOwnerChanging(global::System.Int32 value);
        partial void OnOwnerChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Slot
        {
            get
            {
                return _Slot;
            }
            set
            {
                OnSlotChanging(value);
                ReportPropertyChanging("Slot");
                _Slot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Slot");
                OnSlotChanged();
            }
        }
        private global::System.Int16 _Slot;
        partial void OnSlotChanging(global::System.Int16 value);
        partial void OnSlotChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EquipID
        {
            get
            {
                return _EquipID;
            }
            set
            {
                OnEquipIDChanging(value);
                ReportPropertyChanging("EquipID");
                _EquipID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EquipID");
                OnEquipIDChanged();
            }
        }
        private global::System.Int32 _EquipID;
        partial void OnEquipIDChanging(global::System.Int32 value);
        partial void OnEquipIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Upgrades
        {
            get
            {
                return _Upgrades;
            }
            set
            {
                OnUpgradesChanging(value);
                ReportPropertyChanging("Upgrades");
                _Upgrades = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Upgrades");
                OnUpgradesChanged();
            }
        }
        private global::System.Byte _Upgrades;
        partial void OnUpgradesChanging(global::System.Byte value);
        partial void OnUpgradesChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte IncStr
        {
            get
            {
                return _IncStr;
            }
            set
            {
                OnIncStrChanging(value);
                ReportPropertyChanging("IncStr");
                _IncStr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncStr");
                OnIncStrChanged();
            }
        }
        private global::System.Byte _IncStr;
        partial void OnIncStrChanging(global::System.Byte value);
        partial void OnIncStrChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte IncEnd
        {
            get
            {
                return _IncEnd;
            }
            set
            {
                OnIncEndChanging(value);
                ReportPropertyChanging("IncEnd");
                _IncEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncEnd");
                OnIncEndChanged();
            }
        }
        private global::System.Byte _IncEnd;
        partial void OnIncEndChanging(global::System.Byte value);
        partial void OnIncEndChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte IncDex
        {
            get
            {
                return _IncDex;
            }
            set
            {
                OnIncDexChanging(value);
                ReportPropertyChanging("IncDex");
                _IncDex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncDex");
                OnIncDexChanged();
            }
        }
        private global::System.Byte _IncDex;
        partial void OnIncDexChanging(global::System.Byte value);
        partial void OnIncDexChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte IncInt
        {
            get
            {
                return _IncInt;
            }
            set
            {
                OnIncIntChanging(value);
                ReportPropertyChanging("IncInt");
                _IncInt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncInt");
                OnIncIntChanged();
            }
        }
        private global::System.Byte _IncInt;
        partial void OnIncIntChanging(global::System.Byte value);
        partial void OnIncIntChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte IncSpr
        {
            get
            {
                return _IncSpr;
            }
            set
            {
                OnIncSprChanging(value);
                ReportPropertyChanging("IncSpr");
                _IncSpr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IncSpr");
                OnIncSprChanged();
            }
        }
        private global::System.Byte _IncSpr;
        partial void OnIncSprChanging(global::System.Byte value);
        partial void OnIncSprChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Expires
        {
            get
            {
                return _Expires;
            }
            set
            {
                OnExpiresChanging(value);
                ReportPropertyChanging("Expires");
                _Expires = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Expires");
                OnExpiresChanged();
            }
        }
        private Nullable<global::System.DateTime> _Expires;
        partial void OnExpiresChanging(Nullable<global::System.DateTime> value);
        partial void OnExpiresChanged();

        #endregion

        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_Equip_Character", "Character")]
        public Character Character
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Equip_Character", "Character").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Equip_Character", "Character").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Character> CharacterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Equip_Character", "Character");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Character>("Zepheus.Database.FK_Equip_Character", "Character", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Zepheus.Database", Name="DatabaseItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DatabaseItem : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues DatabaseItem-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft ID.</param>
        /// <param name="owner">Anfangswert der Eigenschaft Owner.</param>
        /// <param name="objectID">Anfangswert der Eigenschaft ObjectID.</param>
        /// <param name="slot">Anfangswert der Eigenschaft Slot.</param>
        /// <param name="amount">Anfangswert der Eigenschaft Amount.</param>
        public static DatabaseItem CreateDatabaseItem(global::System.Int32 id, global::System.Int32 owner, global::System.Int32 objectID, global::System.Int16 slot, global::System.Int16 amount)
        {
            DatabaseItem databaseItem = new DatabaseItem();
            databaseItem.ID = id;
            databaseItem.Owner = owner;
            databaseItem.ObjectID = objectID;
            databaseItem.Slot = slot;
            databaseItem.Amount = amount;
            return databaseItem;
        }

        #endregion

        #region Einfache Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Owner
        {
            get
            {
                return _Owner;
            }
            set
            {
                OnOwnerChanging(value);
                ReportPropertyChanging("Owner");
                _Owner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Owner");
                OnOwnerChanged();
            }
        }
        private global::System.Int32 _Owner;
        partial void OnOwnerChanging(global::System.Int32 value);
        partial void OnOwnerChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ObjectID
        {
            get
            {
                return _ObjectID;
            }
            set
            {
                OnObjectIDChanging(value);
                ReportPropertyChanging("ObjectID");
                _ObjectID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ObjectID");
                OnObjectIDChanged();
            }
        }
        private global::System.Int32 _ObjectID;
        partial void OnObjectIDChanging(global::System.Int32 value);
        partial void OnObjectIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Slot
        {
            get
            {
                return _Slot;
            }
            set
            {
                OnSlotChanging(value);
                ReportPropertyChanging("Slot");
                _Slot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Slot");
                OnSlotChanged();
            }
        }
        private global::System.Int16 _Slot;
        partial void OnSlotChanging(global::System.Int16 value);
        partial void OnSlotChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Int16 _Amount;
        partial void OnAmountChanging(global::System.Int16 value);
        partial void OnAmountChanged();

        #endregion

        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_Item_Character1", "Character")]
        public Character Character
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Item_Character1", "Character").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Item_Character1", "Character").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Character> CharacterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Item_Character1", "Character");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Character>("Zepheus.Database.FK_Item_Character1", "Character", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Zepheus.Database", Name="DatabaseSkill")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DatabaseSkill : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues DatabaseSkill-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft ID.</param>
        /// <param name="owner">Anfangswert der Eigenschaft Owner.</param>
        /// <param name="skillID">Anfangswert der Eigenschaft SkillID.</param>
        /// <param name="upgrades">Anfangswert der Eigenschaft Upgrades.</param>
        /// <param name="isPassive">Anfangswert der Eigenschaft IsPassive.</param>
        public static DatabaseSkill CreateDatabaseSkill(global::System.Int32 id, global::System.Int32 owner, global::System.Int16 skillID, global::System.Int16 upgrades, global::System.Boolean isPassive)
        {
            DatabaseSkill databaseSkill = new DatabaseSkill();
            databaseSkill.ID = id;
            databaseSkill.Owner = owner;
            databaseSkill.SkillID = skillID;
            databaseSkill.Upgrades = upgrades;
            databaseSkill.IsPassive = isPassive;
            return databaseSkill;
        }

        #endregion

        #region Einfache Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Owner
        {
            get
            {
                return _Owner;
            }
            set
            {
                OnOwnerChanging(value);
                ReportPropertyChanging("Owner");
                _Owner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Owner");
                OnOwnerChanged();
            }
        }
        private global::System.Int32 _Owner;
        partial void OnOwnerChanging(global::System.Int32 value);
        partial void OnOwnerChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 SkillID
        {
            get
            {
                return _SkillID;
            }
            set
            {
                OnSkillIDChanging(value);
                ReportPropertyChanging("SkillID");
                _SkillID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SkillID");
                OnSkillIDChanged();
            }
        }
        private global::System.Int16 _SkillID;
        partial void OnSkillIDChanging(global::System.Int16 value);
        partial void OnSkillIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Upgrades
        {
            get
            {
                return _Upgrades;
            }
            set
            {
                OnUpgradesChanging(value);
                ReportPropertyChanging("Upgrades");
                _Upgrades = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Upgrades");
                OnUpgradesChanged();
            }
        }
        private global::System.Int16 _Upgrades;
        partial void OnUpgradesChanging(global::System.Int16 value);
        partial void OnUpgradesChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPassive
        {
            get
            {
                return _IsPassive;
            }
            set
            {
                OnIsPassiveChanging(value);
                ReportPropertyChanging("IsPassive");
                _IsPassive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPassive");
                OnIsPassiveChanged();
            }
        }
        private global::System.Boolean _IsPassive;
        partial void OnIsPassiveChanging(global::System.Boolean value);
        partial void OnIsPassiveChanged();

        #endregion

        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_Skills_Character", "Character")]
        public Character Character
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Skills_Character", "Character").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Skills_Character", "Character").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Character> CharacterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Skills_Character", "Character");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Character>("Zepheus.Database.FK_Skills_Character", "Character", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Zepheus.Database", Name="Guild")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Guild : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Guild-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft ID.</param>
        public static Guild CreateGuild(global::System.Int32 id)
        {
            Guild guild = new Guild();
            guild.ID = id;
            return guild;
        }

        #endregion

        #region Einfache Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_Character_Guild", "Character")]
        public EntityCollection<Character> Characters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Character>("Zepheus.Database.FK_Character_Guild", "Character");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Character>("Zepheus.Database.FK_Character_Guild", "Character", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Zepheus.Database", Name="Party")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Party : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues Party-Objekt.
        /// </summary>
        /// <param name="charNo">Anfangswert der Eigenschaft CharNo.</param>
        /// <param name="masterNo">Anfangswert der Eigenschaft MasterNo.</param>
        /// <param name="partyNo">Anfangswert der Eigenschaft PartyNo.</param>
        /// <param name="partyGroup">Anfangswert der Eigenschaft PartyGroup.</param>
        public static Party CreateParty(global::System.Int32 charNo, global::System.Int32 masterNo, global::System.Int32 partyNo, global::System.Int32 partyGroup)
        {
            Party party = new Party();
            party.CharNo = charNo;
            party.MasterNo = masterNo;
            party.PartyNo = partyNo;
            party.PartyGroup = partyGroup;
            return party;
        }

        #endregion

        #region Einfache Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CharNo
        {
            get
            {
                return _CharNo;
            }
            set
            {
                if (_CharNo != value)
                {
                    OnCharNoChanging(value);
                    ReportPropertyChanging("CharNo");
                    _CharNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CharNo");
                    OnCharNoChanged();
                }
            }
        }
        private global::System.Int32 _CharNo;
        partial void OnCharNoChanging(global::System.Int32 value);
        partial void OnCharNoChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MasterNo
        {
            get
            {
                return _MasterNo;
            }
            set
            {
                OnMasterNoChanging(value);
                ReportPropertyChanging("MasterNo");
                _MasterNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MasterNo");
                OnMasterNoChanged();
            }
        }
        private global::System.Int32 _MasterNo;
        partial void OnMasterNoChanging(global::System.Int32 value);
        partial void OnMasterNoChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PartyNo
        {
            get
            {
                return _PartyNo;
            }
            set
            {
                OnPartyNoChanging(value);
                ReportPropertyChanging("PartyNo");
                _PartyNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartyNo");
                OnPartyNoChanged();
            }
        }
        private global::System.Int32 _PartyNo;
        partial void OnPartyNoChanging(global::System.Int32 value);
        partial void OnPartyNoChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PartyGroup
        {
            get
            {
                return _PartyGroup;
            }
            set
            {
                OnPartyGroupChanging(value);
                ReportPropertyChanging("PartyGroup");
                _PartyGroup = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartyGroup");
                OnPartyGroupChanged();
            }
        }
        private global::System.Int32 _PartyGroup;
        partial void OnPartyGroupChanging(global::System.Int32 value);
        partial void OnPartyGroupChanged();

        #endregion

        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_Party_Character", "Character")]
        public Character Character
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Party_Character", "Character").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Party_Character", "Character").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Character> CharacterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_Party_Character", "Character");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Character>("Zepheus.Database.FK_Party_Character", "Character", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Zepheus.Database", Name="PartyMatchingSystem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PartyMatchingSystem : EntityObject
    {
        #region Factory-Methode
    
        /// <summary>
        /// Erstellt ein neues PartyMatchingSystem-Objekt.
        /// </summary>
        /// <param name="id">Anfangswert der Eigenschaft ID.</param>
        /// <param name="owner">Anfangswert der Eigenschaft Owner.</param>
        /// <param name="name">Anfangswert der Eigenschaft Name.</param>
        /// <param name="message">Anfangswert der Eigenschaft Message.</param>
        /// <param name="datetime">Anfangswert der Eigenschaft Datetime.</param>
        public static PartyMatchingSystem CreatePartyMatchingSystem(global::System.Int32 id, global::System.Int32 owner, global::System.String name, global::System.String message, global::System.DateTime datetime)
        {
            PartyMatchingSystem partyMatchingSystem = new PartyMatchingSystem();
            partyMatchingSystem.ID = id;
            partyMatchingSystem.Owner = owner;
            partyMatchingSystem.Name = name;
            partyMatchingSystem.Message = message;
            partyMatchingSystem.Datetime = datetime;
            return partyMatchingSystem;
        }

        #endregion

        #region Einfache Eigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Owner
        {
            get
            {
                return _Owner;
            }
            set
            {
                OnOwnerChanging(value);
                ReportPropertyChanging("Owner");
                _Owner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Owner");
                OnOwnerChanged();
            }
        }
        private global::System.Int32 _Owner;
        partial void OnOwnerChanging(global::System.Int32 value);
        partial void OnOwnerChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Datetime
        {
            get
            {
                return _Datetime;
            }
            set
            {
                OnDatetimeChanging(value);
                ReportPropertyChanging("Datetime");
                _Datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Datetime");
                OnDatetimeChanged();
            }
        }
        private global::System.DateTime _Datetime;
        partial void OnDatetimeChanging(global::System.DateTime value);
        partial void OnDatetimeChanged();

        #endregion

        #region Navigationseigenschaften
    
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Zepheus.Database", "FK_PartyMatchingSystem_Character", "Character")]
        public Character Character
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_PartyMatchingSystem_Character", "Character").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_PartyMatchingSystem_Character", "Character").Value = value;
            }
        }
        /// <summary>
        /// Keine Dokumentation für Metadaten verfügbar.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Character> CharacterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Character>("Zepheus.Database.FK_PartyMatchingSystem_Character", "Character");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Character>("Zepheus.Database.FK_PartyMatchingSystem_Character", "Character", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// Keine Dokumentation für Metadaten verfügbar.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Zepheus.Database", Name="ComplexType1")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ComplexType1 : ComplexObject
    {
    }

    #endregion

}
